networks:
  dev:

services:
  frontend:
    build:
      context: ./wwwhypda-frontendV2
      dockerfile: Dockerfile
    env_file:
      - ./wwwhypda-frontendV2/.env.production
    volumes:
      - frontend_dist:/frontend-dist
    command: sh -c "npm run build && cp -r /app/dist/. /frontend-dist"
    working_dir: /app
    restart: "no"
    networks:
      - dev

  backend:
    build:
      context: .
      dockerfile: ./wwwhypda-backend/Dockerfile
    env_file:
      - ./wwwhypda-backend/env.prod
    restart: unless-stopped
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - dev

volumes:
  frontend_dist: