networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      # !!! for https
      # - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    
  frontend:
    build:
      context: ./wwwhypda-frontend

    env_file:
      - ./wwwhypda-frontend/.env

    networks:
      - dev

  backend:
    build:
      context: .
      dockerfile: ./wwwhypda-backend/Dockerfile
    
    env_file:
      - ./wwwhypda-backend/env.configs

    networks:
      - dev
