networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      # !!! for https
      # - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    

  backend:
    build:
      context: ./wwwhypda-backend
    
    env_file:
      - ./wwwhypda-backend/env.configs

    networks:
      - dev

  frontend:
    build:
      context: ./wwwhypda-frontend
    networks:
      - dev